### PR TITLE
Add SLF4J and Log4J logging support

### PR DESCRIPTION
**Pull request by lukacupic**
PR for #6

### CODE REVIEW

**Comment by charlesmike** [comment]
@lukacupic thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@lukacupic Looks good. Just one remark: always add a description to your PR and reference the ticket you are solving. This is a small PR so I just referenced the ticket.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by lukacupic** [comment]
> @lukacupic Looks good. Just one remark: always add a description to your PR and reference the ticket you are solving. This is a small PR so I just referenced the ticket.

Understood, makes sense.

**Pull request merged**
