### PR TITLE
#16 TodoParser now accepts estimations in minutes only.

### LINKED ISSUE #16: Estimation format should only accept minutes.
Estimations should have minutes in the format of `m`,`min` or `mins` :

- `#100:30m`
- `#100:30min`
- `#100:30mins`

https://github.com/self-xdsd/todo-finder-cli/blob/5d4186685444cdbd3da4e884250f3543e88a458e/src/main/java/com/selfxdsd/todocli/TodoParser.java#L96

### PR DESCRIPTION
**Pull request by criske**
- valid minutes formats: "m","min","mins".

Fixes #16

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty needed.

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@criske thank you!

**Comment by amihaiemil** [comment]
@rultor merge it

**Pull request merged**
