### PR TITLE
#35 Allow Any File to be Parsed.

### LINKED ISSUE #35: Allow Any File to be Parsed
I think we should remove that if statement (``if file JS or Java``) and allow the parsing of any file. 
This will cover the majority of programming languages and for others simply no todos will be found.

### PR DESCRIPTION
**Pull request by criske**
closes #35

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty needed

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@criske thanks!

**Pull request merged**
