### PR TITLE
#7 TodoVisitor accepts js files too.

### LINKED ISSUE #7: Allow ".js" files to be parsed for todos.
https://github.com/self-xdsd/todo-finder-cli/blob/a44545092b6589f3e805fe4e4b434642f7a73466/src/main/java/com/selfxdsd/todocli/TodoVisitor.java#L74

Sometimes frontend of `self-xdsd/self-web` has [todos](https://github.com/self-xdsd/self-web/issues/170) in  js files.

### PR DESCRIPTION
**Pull request by criske**
closes #7

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
@amihaiemil no bounty needed.

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@criske thank you!

**Comment by amihaiemil** [comment]
@rultor merge it

**Pull request merged**
