### PR TITLE
Update TODO Json: rename `ticket` to `originatingTicket` and add the …

### LINKED ISSUE #22: Update TODO Json
At the moment the JSON todo output is:

```java
{
    "ticket": "#15",
    "estimate": 15,
    "body": "This a todo in a js file and has a multiline body.",
    "lines": "2-3",
    "file": "./target/test-classes/js/JsTodos.js"
}
```

Two changes are needed: rename ``ticket`` to ``originatingTicket`` and add the TODO's ID.

### PR DESCRIPTION
**Pull request by lukacupic**
Fixes #22.

I deliberately didn't make any changes to the JsonTodo object. I only updated @criske's JsonTodosSerializer and its corresponding test because it's the one that matched @amihaiemil's description.

### CODE REVIEW

**Comment by charlesmike** [comment]
@lukacupic thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by criske** [comment]
@lukacupic That test will be changed anyway in #23 :D . I think is safe to update JsonTodo, I'll wait for this to be merged first.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by amihaiemil** [comment]
@rultor merge it please

**Pull request merged**
